# Generated by Django 5.2.1 on 2025-06-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_usuario_doctor_apellido_doctor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
