# Generated by Django 5.2.1 on 2025-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
