# Generated by Django 5.2.1 on 2025-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='dia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='citas',
            name='hora_final',
            field=models.TimeField(null=True),
        ),
    ]
