# Generated by Django 5.2.1 on 2025-05-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='segundo_apellido',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='segundo_nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
